version: "3.7"

services:

  webapp:
    build:
      context: ./
      dockerfile: Dockerfile.webapp
    image: webapp:v7.0
    ports:
      - "8011:8011"
    volumes:
      - "./:/code"
    environment:
      - HOST=0.0.0.0
      - PORT=8011

  iiot:
    build:
      context: ./
      dockerfile: Dockerfile.iiot
    image: iiot:v1.0
    ports:
      - "8013:8013"
    volumes:
      - "./:/code"
    environment:
      - HOST=0.0.0.0
      - PORT=8013